iitc.compat.makeAliases({
  REFRESH: 'iitc.config.REFRESH',
  ZOOM_LEVEL_ADJ: 'iitc.config.ZOOM_LEVEL_ADJ',
  ON_MOVE_REFRESH: 'iitc.config.ON_MOVE_REFRESH',
  MINIMUM_OVERRIDE_REFRESH: 'iitc.config.MINIMUM_OVERRIDE_REFRESH',
  REFRESH_GAME_SCORE: 'iitc.config.REFRESH_GAME_SCORE',
  MAX_IDLE_TIME: 'iitc.config.MAX_IDLE_TIME',
  HIDDEN_SCROLLBAR_ASSUMED_WIDTH: 'iitc.config.HIDDEN_SCROLLBAR_ASSUMED_WIDTH',
  SIDEBAR_WIDTH: 'iitc.config.SIDEBAR_WIDTH',
  CHAT_REQUEST_SCROLL_TOP: 'iitc.config.CHAT_REQUEST_SCROLL_TOP',
  CHAT_SHRINKED: 'iitc.config.CHAT_SHRINKED',
  FIELD_MU_DISPLAY_AREA_ZOOM_RATIO: 'iitc.config.FIELD_MU_DISPLAY_AREA_ZOOM_RATIO',
  FIELD_MU_DISPLAY_POINT_TOLERANCE: 'iitc.config.FIELD_MU_DISPLAY_POINT_TOLERANCE',

  COLOR_SELECTED_PORTAL: 'iitc.colors.SELECTED_PORTAL',
  COLORS: 'iitc.colors.TEAMS',
  COLORS_LVL: 'iitc.colors.LEVELS',
  COLORS_MOD: 'iitc.colors.MODS',

  ACCESS_INDICATOR_COLOR: 'iitc.colors.ACCESS_INDICATOR',
  RANGE_INDICATOR_COLOR: 'iitc.colors.RANGE_INDICATOR',

  iitcBuildDate: 'iitc.constants.BUILD_DATE',
  MOD_TYPE: 'iitc.constants.MOD_TYPES',
  MIN_ZOOM: 'iitc.constants.MIN_ZOOM',
  DEFAULT_PORTAL_IMG: 'iitc.constants.DEFAULT_PORTAL_IMG',
  NOMINATIM: 'iitc.constants.NOMINATIM',

  RESO_NRG: 'iitc.constants.RESO_NRG',
  HACK_RANGE: 'iitc.constants.HACK_RANGE',
  OCTANTS: 'iitc.constants.OCTANTS',
  OCTANTS_ARROW: 'iitc.constants.OCTANTS_ARROW',
  DESTROY_RESONATOR: 'iitc.constants.DESTROY_RESONATOR',
  DESTROY_LINK: 'iitc.constants.DESTROY_LINK',
  DESTROY_FIELD: 'iitc.constants.DESTROY_FIELD',
  CAPTURE_PORTAL: 'iitc.constants.CAPTURE_PORTAL',
  DEPLOY_RESONATOR: 'iitc.constants.DEPLOY_RESONATOR',
  COMPLETION_BONUS: 'iitc.constants.COMPLETION_BONUS',
  UPGRADE_ANOTHERS_RESONATOR: 'iitc.constants.UPGRADE_ANOTHERS_RESONATOR',
  MAX_PORTAL_LEVEL: 'iitc.constants.MAX_PORTAL_LEVEL',
  MAX_RESO_PER_PLAYER: 'iitc.constants.MAX_RESO_PER_PLAYER',

  TEAM_NONE: 'iitc.constants.TEAM_NONE',
  TEAM_RES: 'iitc.constants.TEAM_RES',
  TEAM_ENL: 'iitc.constants.TEAM_ENL',
  TEAM_TO_CSS: 'iitc.constants.TEAM_TO_CSS',

  SLOT_TO_LAT: 'iitc.constants.SLOT_TO_LAT',
  SLOT_TO_LNG: 'iitc.constants.SLOT_TO_LNG',
  EARTH_RADIUS: 'iitc.constants.EARTH_RADIUS',
  DEG2RAD: 'iitc.constants.DEG2RAD',

  refreshTimeout: 'iitc.refreshTimeout',
  urlPortal: 'iitc.urlPortal',
  urlPortalLL: 'iitc.urlPortalLL',
  selectedPortal: 'iitc.selectedPortal',
  portalRangeIndicator: 'iitc.portalRangeIndicator',
  portalAccessIndicator: 'iitc.portalAccessIndicator',
  mapRunsUserAction: 'iitc.mapRunsUserAction',

  portals: 'iitc.portals',
  links: 'iitc.links',
  fields: 'iitc.fields',
  resonators: 'iitc.resonators',

  overlayStatus: 'iitc.overlayStatus',
});
