py_binary(
    name="iitc_processor",
    srcs=["iitc_processor.py"],
    visibility=["//visibility:public"],
)

exports_files(
    [
        "core_wrapper.js",
        "plugin_wrapper.js",
    ],
    visibility=["//visibility:public"],
)
